### PR TITLE
Additional REST API methods

### PR DESCRIPTION
**Pull request by christiansmith**

### CODE REVIEW

**Comment by vsimonian** [comment]
This PR's scope is very ambitious. Proposition:

1. Freeze further development on this branch
2. Review
3. Merge

Further additions to the API should have PRs per feature (i.e. users would be an individual PR)

**Comment by christiansmith** [comment]
@vsimonian it's ready to merge anyways. Currently covers the entire REST API exposed by Anvil Connect. I believe the API needs to grow on the server side, but for now this is complete and awaiting review.

**Comment by vsimonian** [comment]
Sounds good! When I get back let's do a code review. :)

**Comment by vsimonian** [comment]
LGTM, but let's consider keeping scope on the PRs down in the future. I can't be as fully confident that I've reviewed it as thoroughly.

[LGTM](http://lgtm.in/i/gqFLCSdDn)

**Pull request merged**
